[package]
name = "imgui-wgpu"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Steven Wittens <steven@acko.net>"]
edition = "2018"
description = "A wgpu render backend for imgui-rs."
documentation = "https://docs.rs/imgui-wgpu/"
homepage = "https://github.com/Yatekii/imgui-wgpu-rs"
repository = "https://github.com/Yatekii/imgui-wgpu-rs"
readme = "README.md"
categories = ["gui", "graphics", "rendering", "rendering::graphics-api"]
keywords = ["gui", "graphics", "wgpu", "imgui"]
license = "MIT OR Apache-2.0"

# [features]
# default = []
# metal = ["wgpu/metal"]
# dx11 = ["wgpu/dx11"]
# dx12 = ["wgpu/dx12"]
# vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
glsl-to-spirv = "0.1"
log = "0.4"
imgui = "0.2.0"

[dev-dependencies]
winit = "0.20.0-alpha3"
raw-window-handle = "0.1"
env_logger = "0.5"

[dev-dependencies.imgui-winit-support]
version = "0.2.0"
default-features = false
features = ["winit-20"]